### ISSUE TITLE
Docker container not outputting from print statements

### ISSUE THREAD

**Issue by subnomo** [osuosl/timesync-frontend-flask#44]
Any `print` statements aren't being displayed when the application is run in a docker container. It works fine when run regularly.

**Comment by matthewrsj** [comment]
Please explain _why_ this is an issue in the issue description. When I first read this I thought:
1. We don't need print statements, this is a web app
2. Oh, he means for debugging, but why not just make the change when you need to debug?
3. Oh, because docker isn't our _production_ environment, it is our _debugging/development_ environment, therefore debug statements should show up be default.

Conclusion: This is a good issue because it allows print statements to display when we want to debug code.

Other devs may be quicker to reach that conclusion than I am, but it would be nice if the issue description did the work for me.

**Comment by subnomo** [comment]
@matthewrsj Will do next time, sorry about that. :sweat:
